title: "ROOT OF EVIL"
description: "By me"
theme: minima
url: "https://moon-harvest.github.io"
baseurl: ""
permalink: /:title/

minima:
  skin: dark

markdown: kramdown
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
